Repository SubnauticaModding/QModManager, pull requests merged in 2019-01, with the labels that each got.

#34 Adding support and instructions for mac users
  Mac Installation/0Harmony.dll
  Mac Installation/Mono.Cecil.dll
  Mac Installation/QModInstaller.dll
  Mac Installation/QModManager.exe
  Mac Installation/README.md
  README.md
Labels: Status: Completed, Type: Maintenance

#39 Prefab debugger changes
  Prefab Debugger/HierarchyItem.cs
  Prefab Debugger/LogMessage.cs
  Prefab Debugger/Prefab Debugger.csproj
  Prefab Debugger/PrefabDebugger.cs
  Prefab Debugger/PrefabDebugger.unity3d
  Prefab Debugger/Properties/AssemblyInfo.cs
  Prefab Debugger/README.md
  Prefab Debugger/Tree.cs
  QModManager.sln
  QModManager/Patcher.cs
Labels: Status: Completed, Status: Review Needed, Type: Maintenance

#29 Version check
  Executable/Program.cs
  Installer/QModInstaller.dll
  Installer/QModManager.exe
  Installer/QModManager_Setup.exe
  Installer/QModsInstallerScript.iss
  Mac Installation/0Harmony.dll
  Mac Installation/Mono.Cecil.dll
  QModManager/Dialog.cs
  QModManager/Hooks.cs
  QModManager/Injector.cs
  QModManager/Patcher.cs
  QModManager/QModManager.csproj
  QModManager/VersionCheck.cs
  latest-version.txt
Labels: Status: Completed, Type: Enhancement

#40 Detect mac install and fix simple things
  Executable/Program.cs
  QModManager/Injector.cs
  QModManager/Patcher.cs
Labels: Status: In Progress, Type: Maintenance
