Repository SubnauticaModding/QModManager, pull requests merged in 2019-05, with the labels that each got.

#77 QModAPI: Dependency injection, ability to specifiy QModManager as a VersionDependency, .xml documentation
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Installer/InstallerExtensions.dll
  Installer/QModsInstallerScript.iss
  Mac Installation/Info.txt
  Mac Installation/README.md
  QModManager/API/Messages.cs
  QModManager/API/QModAPI.cs
  QModManager/API/QModHooks.cs
  QModManager/EntryPoint.cs
  QModManager/Hooks.cs
  QModManager/Legacy/PatchManager.cs
  QModManager/Obsolete/Hooks.cs
  QModManager/Obsolete/PatchManager.cs
  QModManager/Patcher.cs
  QModManager/PirateCheck.cs
  QModManager/QMod.cs
  QModManager/QModAPI.cs
  QModManager/QModManager.csproj
  QModManager/Utility/Logger.cs
  QModManager/Utility/ReflectionHelper.cs
  QModManager/VersionCheck.cs
Labels: Type: Enhancement

#73 2.1 (will not be released)
  .gitignore
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Data/latest-version.txt
  Dependencies/README.md
  Dependencies/SemVer.dll
  Executable/Injector.cs
  Executable/Program.cs
  Executable/Properties/AssemblyInfo.cs
  Installer/InstallerExtensions.dll
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  Mac Installation/0Harmony.dll
  Mac Installation/Info.txt
  Mac Installation/Mono.Cecil.dll
  Mac Installation/QModInstaller.dll
  Mac Installation/QModManager.exe
  Mac Installation/QModsInstaller.pkgproj
  Mac Installation/README.md
  Mac Installation/background.png
  QModManager/API/Messages.cs
  QModManager/API/QModAPI.cs
  QModManager/API/QModHooks.cs
  QModManager/Dialog.cs
  QModManager/EntryPoint.cs
  QModManager/Hooks.cs
  QModManager/NitroxCheck.cs
  QModManager/Obsolete/Hooks.cs
  QModManager/Obsolete/PatchManager.cs
  QModManager/OptionsManager.cs
  QModManager/PatchManager.cs
  QModManager/Patcher.cs
  QModManager/PirateCheck.cs
  QModManager/Prefab Debugger/PrefabDebugger.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QMod.cs
  QModManager/QModManager.csproj
  QModManager/Utility/IOUtilities.cs
  QModManager/Utility/Logger.cs
  QModManager/Utility/NetworkUtilities.cs
  QModManager/Utility/ReflectionHelper.cs
  QModManager/VersionCheck.cs
  README.md
  Unit Tests/SortModTests.cs
  Unit Tests/Sorting.cs
  Unit Tests/Unit Tests.csproj
  Unit Tests/VersionDependencies.cs
  latest-version.txt
Labels: Status: Pending, Type: Enhancement, Type: Maintenance

#95 Update logger
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.exe
  QModManager/API/SMLHelper/Initializer.cs
  QModManager/Utility/Logger.cs
Labels: Type: Maintenance

#97 Add license to installer
  Build/QModManager_Setup.exe
  Installer/License.txt
  Installer/QModsInstallerScript.iss
Labels: Type: Maintenance

#100 SMLHelper splits and updates
  QModManager/API/SMLHelper/Assets/Buildable.cs
  QModManager/API/SMLHelper/Assets/PDAItem.cs
  QModManager/API/SMLHelper/Assets/Spawnable.cs
  QModManager/API/SMLHelper/Crafting/CraftingNode.cs
  QModManager/API/SMLHelper/Crafting/ModCraftTreeCraft.cs
  QModManager/API/SMLHelper/Crafting/ModCraftTreeFamily.cs
  QModManager/API/SMLHelper/Crafting/ModCraftTreeLinkingNode.cs
  QModManager/API/SMLHelper/Crafting/ModCraftTreeNode.cs
  QModManager/API/SMLHelper/Crafting/ModCraftTreeRoot.cs
  QModManager/API/SMLHelper/Crafting/ModCraftTreeTab.cs
  QModManager/API/SMLHelper/Crafting/Node.cs
  QModManager/API/SMLHelper/Crafting/TabNode.cs
  QModManager/QModManager.csproj
Labels: Type: Maintenance

#99 dev/Unity2018 - Updating projects to Unity2018 assemblies
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.exe
  Dependencies/README.md
  Dependencies/UnityEngine.CoreModule.dll
  Dependencies/UnityEngine.PhysicsModule.dll
  Dependencies/UnityEngine.UI.dll
  Dependencies/UnityEngine.dll
  Examples/Examples.csproj
  QModManager/API/SMLHelper/Utility/ImageUtils.cs
  QModManager/QModManager.csproj
Labels: Status: Completed, Type: Maintenance
