Repository SubnauticaModding/QModManager, pull requests merged in 2020-08, with the labels that each got.

#163 Proper recursive dependency checks
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/QModFactory.cs
Labels: Priority: Critical, Type: Bug

#164 Version strings now all implicity treated as having 4 groups with trailing zeros
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.QMMHarmonyShimmer.dll
  Build/QModManager.QMMLoader.dll
  Build/QModManager.QModPluginGenerator.dll
  Build/QModManager.UnityAudioFixer.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Build/VortexPackage.zip
  Data/latest-version.txt
  Executable/Properties/AssemblyInfo.cs
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QMMHarmonyShimmer/Properties/AssemblyInfo.cs
  QMMLoader/Properties/AssemblyInfo.cs
  QModManager/API/RequiredQMod.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QModManager.csproj
  QModManager/Utility/VersionParser.cs
  QModPluginEmulator/Properties/AssemblyInfo.cs
  QModPluginEmulator/QModPluginGenerator.cs
  Unit Tests/ManifestValidatorTests.cs
  Unit Tests/QModFactoryTests.cs
  Unit Tests/RequiredQModTests.cs
  Unit Tests/Unit Tests.csproj
  UnityAudioFixer/Properties/AssemblyInfo.cs
Labels: Priority: High, Type: Bug

#165 QModManager 4.0.1 - Hotfix for version dependency issues
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.QMMHarmonyShimmer.dll
  Build/QModManager.QMMLoader.dll
  Build/QModManager.QModPluginGenerator.dll
  Build/QModManager.UnityAudioFixer.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Build/VortexPackage.zip
  Data/latest-version.txt
  Executable/Properties/AssemblyInfo.cs
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QMMHarmonyShimmer/Properties/AssemblyInfo.cs
  QMMLoader/Properties/AssemblyInfo.cs
  QModManager/API/RequiredQMod.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QModManager.csproj
  QModManager/Utility/Dialog.cs
  QModManager/Utility/VersionParser.cs
  QModPluginEmulator/Properties/AssemblyInfo.cs
  QModPluginEmulator/QModPluginGenerator.cs
  Unit Tests/ManifestValidatorTests.cs
  Unit Tests/QModFactoryTests.cs
  Unit Tests/RequiredQModTests.cs
  Unit Tests/Unit Tests.csproj
  UnityAudioFixer/Properties/AssemblyInfo.cs
Labels: Priority: Critical, Type: Bug

#171 Fix tree sort
  QModManager/DataStructures/SortedCollection.cs
  Unit Tests/SortedTreeTests.cs
Labels: Priority: High, Type: Bug

#172 Clear BepInEx Cache on QMM Assembly Update
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  QModPluginEmulator/QModPluginGenerator.cs
Labels: Priority: Medium, Type: Bug

#174 Fix logging required mods
  QModManager/Patching/ManifestValidator.cs
Labels: Priority: Medium, Type: Bug

#175 Update MirrorInternalLogs
  Dependencies/BepInEx/BepInEx/config/MirrorInternalLogs.cfg
  Dependencies/BepInEx/BepInEx/patchers/MirrorInternalLogs.dll
Labels: Priority: High, Type: Bug

#178 Update MirrorInternalLogs to r5 release
  Dependencies/BepInEx/BepInEx/patchers/MirrorInternalLogs.dll
Labels: Priority: High, Type: Bug

#182 Update BepInEx to v5.3
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.QMMHarmonyShimmer.dll
  Build/QModManager.QMMLoader.dll
  Build/QModManager.QModPluginGenerator.dll
  Build/QModManager.UnityAudioFixer.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Build/VortexPackage.zip
  Data/latest-version.txt
  Dependencies/BepInEx/BepInEx/core/0Harmony.dll
  Dependencies/BepInEx/BepInEx/core/0Harmony.xml
  Dependencies/BepInEx/BepInEx/core/BepInEx.Preloader.dll
  Dependencies/BepInEx/BepInEx/core/BepInEx.Preloader.xml
  Dependencies/BepInEx/BepInEx/core/BepInEx.dll
  Dependencies/BepInEx/BepInEx/core/BepInEx.xml
  Dependencies/BepInEx/BepInEx/core/MonoMod.RuntimeDetour.dll
  Dependencies/BepInEx/BepInEx/core/MonoMod.Utils.dll
  Dependencies/BepInEx/BepInEx/core/MonoMod.Utils.xml
  Dependencies/BepInEx/winhttp.dll
  Executable/Properties/AssemblyInfo.cs
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QMMHarmonyShimmer/Properties/AssemblyInfo.cs
  QMMLoader/Properties/AssemblyInfo.cs
  QModManager/Properties/AssemblyInfo.cs
  QModPluginEmulator/Properties/AssemblyInfo.cs
  UnityAudioFixer/Properties/AssemblyInfo.cs
Labels: Priority: High, Type: Bug

#181 QModManager 4.0.2
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.QMMHarmonyShimmer.dll
  Build/QModManager.QMMLoader.dll
  Build/QModManager.QModPluginGenerator.dll
  Build/QModManager.UnityAudioFixer.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Build/VortexPackage.zip
  Data/latest-version.txt
  Dependencies/BepInEx/BepInEx/config/MirrorInternalLogs.cfg
  Dependencies/BepInEx/BepInEx/core/0Harmony.dll
  Dependencies/BepInEx/BepInEx/core/0Harmony.xml
  Dependencies/BepInEx/BepInEx/core/BepInEx.Preloader.dll
  Dependencies/BepInEx/BepInEx/core/BepInEx.Preloader.xml
  Dependencies/BepInEx/BepInEx/core/BepInEx.dll
  Dependencies/BepInEx/BepInEx/core/BepInEx.xml
  Dependencies/BepInEx/BepInEx/core/MonoMod.RuntimeDetour.dll
  Dependencies/BepInEx/BepInEx/core/MonoMod.Utils.dll
  Dependencies/BepInEx/BepInEx/core/MonoMod.Utils.xml
  Dependencies/BepInEx/BepInEx/patchers/MirrorInternalLogs.dll
  Dependencies/BepInEx/winhttp.dll
  Executable/Executable.csproj
  Executable/Properties/AssemblyInfo.cs
  Installer/InstallerExtensions.csproj
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QMMHarmonyShimmer/Properties/AssemblyInfo.cs
  QMMHarmonyShimmer/QMMHarmonyShimmer.cs
  QMMHarmonyShimmer/QModManager.QMMHarmonyShimmer.csproj
  QMMLoader/Properties/AssemblyInfo.cs
  QMMLoader/QModManager.QMMLoader.csproj
  QModManager/Checks/VersionCheck.cs
  QModManager/DataStructures/SortedCollection.cs
  QModManager/Patching/IManifestValidator.cs
  QModManager/Patching/IPluginCollection.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/Patcher.cs
  QModManager/Patching/PluginCollection.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QModManager.csproj
  QModManager/Utility/IOUtilities.cs
  QModPluginEmulator/Properties/AssemblyInfo.cs
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  QModPluginEmulator/QModPluginGenerator.cs
  Unit Tests/QModFactoryTests.cs
  Unit Tests/SortedTreeTests.cs
  UnityAudioFixer/Properties/AssemblyInfo.cs
  UnityAudioFixer/QModManager.UnityAudioFixer.csproj
Labels: Priority: High, Type: Bug, Type: Maintenance
