Repository SubnauticaModding/QModManager, pull requests merged in 2020-01, with the labels that each got.

#121 Move SummaryLogger to QModManager.Utility
  QModManager/QModManager.csproj
  QModManager/Utility/SummaryLogger.cs
Labels: Type: Maintenance

#123 Merge mod: Enable Achievements by AlexejheroYTB
  QModManager/HarmonyPatches/EnableAchievements.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/QModManager.csproj
  README.md
Labels: Type: Enhancement

#126 Merge pull request #126 from SubnauticaModding/dialog
  QModManager/API/ModLoading/ModStatus.cs
  QModManager/Checks/PirateCheck.cs
  QModManager/Checks/VersionCheck.cs
  QModManager/Patching/Initializer.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/ModStatus.cs
  QModManager/Patching/Patcher.cs
  QModManager/Patching/QMod.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Patching/QModPatchMethod.cs
  QModManager/Patching/QModPlaceholder.cs
  QModManager/QModManager.csproj
  QModManager/Utility/Dialog.cs
  QModManager/Utility/Logger.cs
  QModManager/Utility/SummaryLogger.cs
Labels: Type: Enhancement

#128 QModManager 3.0.1 bug fix
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Data/latest-version.txt
  Executable/Properties/AssemblyInfo.cs
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QModManager.sln
  QModManager/Patching/IQModFactory.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/Patcher.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QModManager.csproj
  Unit Tests/QModFactoryTests.cs
  Unit Tests/Unit Tests.csproj
Labels: Type: Bug
