Repository SubnauticaModding/QModManager, pull requests merged in 2020-02, with the labels that each got.

#131 Check types after sorting
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  QModManager/API/ModLoading/QModPatchAttributeBase.cs
  QModManager/Patching/IManifestValidator.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/QMod.cs
  QModManager/Patching/QModFactory.cs
  QModManager/QModManager.csproj
  QModManager/SummaryLogger.cs
  Unit Tests/QModFactoryTests.cs
Labels: Type: Maintenance

#130 QModManager 3.0.2
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Build/UnityEngine.CoreModule.dll
  Data/latest-version.txt
  Dependencies/AssetsTools.NET.dll
  Dependencies/cldb2018.dat
  Executable/AudioFixer.cs
  Executable/Properties/AssemblyInfo.cs
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QModManager/API/ModLoading/QModPatchAttributeBase.cs
  QModManager/Patching/IManifestValidator.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/QMod.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QModManager.csproj
  QModManager/SummaryLogger.cs
  Unit Tests/QModFactoryTests.cs
Labels: Type: Maintenance

#132 BugFix - Load RequiredDependencies BeforeSort
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  QModManager/Patching/QModFactory.cs
  Unit Tests/SortedTreeTests.cs
Labels: Priority: High, Type: Bug

#133 Sorting preferences fix2
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  QModManager/DataStructures/SortedCollection.cs
  QModManager/DataStructures/SortedTreeNode.cs
  QModManager/Patching/Patcher.cs
  QModManager/Patching/QModPlaceholder.cs
  QModManager/SummaryLogger.cs
  Unit Tests/SortedTreeTests.cs
Labels: Priority: High, Type: Bug

#125 Store QModManager configuration in qmodmanager-config.json
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  QModManager/HarmonyPatches/DisableDevErrorReporting.cs
  QModManager/HarmonyPatches/EnableConsoleSetting.cs
  QModManager/HarmonyPatches/UpdateDeveloperMode.cs
  QModManager/OptionsManager.cs
  QModManager/QModManager.csproj
  QModManager/Utility/Config.cs
  QModManager/Utility/Logger.cs
  QModManager/Utility/PlayerPrefsExtra.cs
Labels: Type: Enhancement
