Repository SubnauticaModding/QModManager, pull requests merged in 2020-06, with the labels that each got.

#148 Updated Logger class.
  QModManager/Utility/Logger.cs
Labels: Type: Enhancement

#149 Dynamic Text Assembly for MainMenuMessages
  QModManager/Utility/MainMenuMessages.cs
Labels: Priority: Critical

#150 JsonUpdate - Update with the latest Newtonsoft.Json.dll
  Dependencies/Newtonsoft.Json.dll
  QModManager/Patching/QMod.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Utility/Config.cs
Labels: Priority: Critical

#151 Sorting bug fix for VersionDependencies
  QModManager/Patching/ManifestValidator.cs
Labels: Type: Bug

#152 QModManager v3.3
  Build/InstallerExtensions.dll
  Build/QModInstaller.dll
  Build/QModInstaller.xml
  Build/QModManager.exe
  Build/QModManager_Setup.exe
  Data/latest-version.txt
  Executable/Properties/AssemblyInfo.cs
  Installer/Properties/AssemblyInfo.cs
  Installer/QModsInstallerScript.iss
  QModManager/Checks/NitroxCheck.cs
  QModManager/HarmonyPatches/EnableConsoleSetting.cs
  QModManager/OptionsManager.cs
  QModManager/Patching/ManifestValidator.cs
  QModManager/Patching/Patcher.cs
  QModManager/Patching/QMod.cs
  QModManager/Patching/QModFactory.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/Utility/Config.cs
  QModManager/Utility/IOUtilities.cs
  QModManager/Utility/Logger.cs
  QModManager/Utility/MainMenuMessages.cs
Labels: Priority: Critical, Type: Enhancement, Type: Issue, Type: Maintenance
