Repository SubnauticaModding/QModManager, pull requests merged in 2021-06, with the labels that each got.

#235 Applying a Regex to trim out the dirty string patterns instead
  QModPluginEmulator/QModPluginGenerator.cs
Labels: Priority: Low, Type: Bug

#239 Refactor log filter
  QModManager/BepInex/Plugins/LogFilter.cs
  QModManager/BepInex/Plugins/QMMLoader.cs
  QModManager/QModManager.csproj
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  QModPluginEmulator/QModPluginGenerator.cs
Labels: Type: Maintenance

#240 Resolve BepInEx plugins being destroyed
  Dependencies/BZ.EXP/BepInEx.cfg
  Dependencies/BZ.STABLE/BepInEx.cfg
  Dependencies/SN.EXP/BepInEx.cfg
  Dependencies/SN.STABLE/BepInEx.cfg
  Installer/BZ.EXP.iss
  Installer/BZ.STABLE.iss
  Installer/SN.EXP.iss
  Installer/SN.STABLE.iss
  QModManager/BepInex/Plugins/QMMLoader.cs
  QModManager/QModManager.csproj
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  QModPluginEmulator/QModPluginGenerator.cs
Labels: Type: Bug, Type: Maintenance

#238 Update to AssetsTools.NET v2.0.9
  Installer/BZ.EXP.iss
  Installer/BZ.STABLE.iss
  Installer/SN.EXP.iss
  Installer/SN.STABLE.iss
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  UnityAudioFixer/QModManager.UnityAudioFixer.csproj
  UnityAudioFixer/UnityAudioFixer.cs
  UnityAudioFixer/packages.config
Labels: Type: Maintenance

#243 Use 7z for build automation
  QModManager.sln
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  QModPluginEmulator/packages.config
  Scripts/QModPluginGenerator-post-build.cmd
Labels: Type: Issue, Type: Maintenance

#242 QModManager 4.2
  Data/latest-version.txt
  Dependencies/BZ.EXP/BepInEx.cfg
  Dependencies/BZ.STABLE/BepInEx.cfg
  Dependencies/BepInEx/BepInEx/patchers/BepInEx.MultiFolderLoader.dll
  Dependencies/BepInEx/doorstop_config.ini
  Dependencies/SN.EXP/BepInEx.cfg
  Dependencies/SN.STABLE/BepInEx.cfg
  Executable/Properties/AssemblyInfo.cs
  Installer/BZ.EXP.iss
  Installer/BZ.STABLE.iss
  Installer/Properties/AssemblyInfo.cs
  Installer/SN.EXP.iss
  Installer/SN.STABLE.iss
  OculusNewtonsoftRedirect/Properties/AssemblyInfo.cs
  QModManager.sln
  QModManager/BepInex/Plugins/LogFilter.cs
  QModManager/BepInex/Plugins/QMMLoader.cs
  QModManager/Properties/AssemblyInfo.cs
  QModManager/QMMLoader.cs
  QModManager/QModManager.csproj
  QModPluginEmulator/Properties/AssemblyInfo.cs
  QModPluginEmulator/QModManager.QModPluginGenerator.csproj
  QModPluginEmulator/QModPluginGenerator.cs
  QModPluginEmulator/packages.config
  Scripts/QModPluginGenerator-post-build.cmd
  UnityAudioFixer/Properties/AssemblyInfo.cs
  UnityAudioFixer/QModManager.UnityAudioFixer.csproj
  UnityAudioFixer/UnityAudioFixer.cs
  UnityAudioFixer/packages.config
Labels: Priority: Medium, Type: Bug, Type: Enhancement, Type: Maintenance

#244 Newtonsoft patcher hotfix
  Data/latest-version.txt
  Executable/Properties/AssemblyInfo.cs
  Installer/BZ.EXP.iss
  Installer/BZ.STABLE.iss
  Installer/Properties/AssemblyInfo.cs
  Installer/SN.EXP.iss
  Installer/SN.STABLE.iss
  OculusNewtonsoftRedirect/Properties/AssemblyInfo.cs
  QModManager/BepInex/Plugins/LogFilter.cs
  QModManager/BepInex/Plugins/QMMLoader.cs
  QModManager/Properties/AssemblyInfo.cs
  QModPluginEmulator/Properties/AssemblyInfo.cs
  QModPluginEmulator/QModPluginGenerator.cs
  UnityAudioFixer/Properties/AssemblyInfo.cs
Labels: Priority: High, Type: Bug
